# -*- coding: utf-8 -*-
"""Data processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vyYIoa90xXDlf0qqF-vonpQxySXsfpD8
"""

import pandas as pd

# Python program to convert
# JSON file to CSV


import json
import csv


# Opening JSON file and loading the data
# into the variable data
with open('data.json') as json_file:
	data = json.load(json_file)
test=data['rows']
print(test) 
	# for i in data['rows']:
	# 	# print(i)
	# 	for j in i.values():
	# 	 	print(j)
test_dict={}
Questions=[]
choices=[]
choice_1=[]
choice_2=[]
choice_3=[]
choice_4=[]
choice_5=[]
for i in test:
	# x=i['row'].values()
	# for j,k in i.items():
	for l in test:
		# print(l)
		# # print(k)
		# # pass
		# print(l['row'])
		for m,o in l['row'].items():
			if m=="question":
				# print(m,o)
				Questions.append(o)
			if m=="choices":
				for w,r in o.items():
					# print(w,r)
					if w=="text":
						# print(w,r)
						choice_1.append(r[0])
						choice_2.append(r[1])
						choice_3.append(r[2])
						choice_4.append(r[3])
						choice_5.append(r[4])
						
				choices.append(o)
		
		
print(len(Questions))
print(len(choices))
print(len(choice_1))
print(len(choice_2))
print(len(choice_3))
print(len(choice_4))
print(len(choice_5))
final_data={'Question':Questions,"choice 1":choice_1,"choice 2":choice_2,"choice 3":choice_3,"choice 4":choice_4}

data_frame=pd.DataFrame(final_data)

data_frame.to_csv("Question_data.csv")

